// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUxP8LpAbkcRh1ZTYvsIXkxn5u56bVjI',
    appId: '1:475338320920:web:5d9b8fc2b13551cd10a76d',
    messagingSenderId: '475338320920',
    projectId: 'namdelivery-admin-store',
    authDomain: 'namdelivery-admin-store.firebaseapp.com',
    storageBucket: 'namdelivery-admin-store.firebasestorage.app',
    measurementId: 'G-YZGPK9HZV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcgGwAtn9-VA8i99GGdUfE_i6moxdEUc',
    appId: '1:475338320920:android:0c0b0c37c169eb8210a76d',
    messagingSenderId: '475338320920',
    projectId: 'namdelivery-admin-store',
    storageBucket: 'namdelivery-admin-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLAg05M_LdkvYiaabZSvW9Mcn0I-q0ok',
    appId: '1:475338320920:ios:c822b0565d04a0a410a76d',
    messagingSenderId: '475338320920',
    projectId: 'namdelivery-admin-store',
    storageBucket: 'namdelivery-admin-store.firebasestorage.app',
    iosBundleId: 'com.workahr.namstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLAg05M_LdkvYiaabZSvW9Mcn0I-q0ok',
    appId: '1:475338320920:ios:c822b0565d04a0a410a76d',
    messagingSenderId: '475338320920',
    projectId: 'namdelivery-admin-store',
    storageBucket: 'namdelivery-admin-store.firebasestorage.app',
    iosBundleId: 'com.workahr.namstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjUxP8LpAbkcRh1ZTYvsIXkxn5u56bVjI',
    appId: '1:475338320920:web:a60e4c1106958c9c10a76d',
    messagingSenderId: '475338320920',
    projectId: 'namdelivery-admin-store',
    authDomain: 'namdelivery-admin-store.firebaseapp.com',
    storageBucket: 'namdelivery-admin-store.firebasestorage.app',
    measurementId: 'G-MW264QM3M9',
  );
}
